# Generated by Django 5.0.6 on 2024-06-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_remove_respuesta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='user',
            field=models.CharField(default='default_user', max_length=100),
            preserve_default=False,
        ),
    ]
